users/urls.py
"""
In dieser Datei wird festgelegt welcher View geladen wird, wenn eine bestimmte URL angesprochen wird
"""
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_project/urls.py
"""web_project URL Configuration

Dies ist die übergeordnete URL-Konfiguration des Projekts. 
Die Liste wird von oben nach unten durchgegangen bis der erste Pattern-Match erfolgt.
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webvinyl.urls')),
    path('', include('users.urls')),
]

webvinyl/urls.py
"""
In dieser Datei wird festgelegt welcher View geladen wird, wenn eine bestimmte URL angesprochen wird
"""

from django.urls import path
from . import views
from .views import  PostUpdateView, PostDeleteView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.base, name='base'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('search_user/', views.search_user, name='search_user'),
    path('found_user/<str:usearch>/', views.found_user, name='found_user'),
    path('search_music/', views.search_music, name='search_music'),
    path('found_music/<int:change>', views.found_music, name='found_music'),
    path('vinyl/<int:masterid>/', views.vinyl_detail, name='vinyl_detail'),
    path('follower/<int:pk>/', views.follower, name='follower'),
    path('following/', views.following, name='following'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('follow/<int:profilekey>/', views.follow, name='follow-user'),
    path('add_vinyl/<int:albumkey>/', views.add_album, name='add-album'),
    path('update/', views.update, name="user-update" ),
    path('like/<int:postkey>', views.like, name="like-post" ),
    path('adv_search/', views.adv_search_music, name='adv_search_music')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webvinyl/models.py
""" In dieser Datei werden die Klassen definiert, aus denen die Datenbank-Tabellen für die "wenvinyl"-App generiert werden """

from django.db import models
from django.utils import timezone
from users.models import Profile
from django.urls import reverse

#Klasse für die Posts der Nutzer
# favourite ermöglicht beliebig vielen Nutzern beliebig viele Posts zu 'liken'
class Post(models.Model):
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    favourite = models.ManyToManyField(Profile, related_name='favourited_by', blank=True)

    def __str__(self):
        return f'{self.pk} {self.date_posted} {self.author.user.username}'

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})
    

#Klasse für die Kommentare auf Posts
class Comment(models.Model):
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return f'{self.date_posted} {self.author.user.username}, comment on {self.post.pk}'

#Klasse für die lokal gespeicherten Albeninformationen
# owner ermöglicht beliebig vielen Nutzern beliebig viele Alben zu besitzen
class Album(models.Model):
    identifier = models.CharField(max_length=20, primary_key=True)
    artist = models.CharField(max_length=50, blank=True)
    title = models.CharField(max_length=50, blank=True)
    cover_uri = models.URLField(blank=True)
    owner = models.ManyToManyField(Profile, related_name='albums', blank=True)


    def __str__(self):
        return self.identifier

webvinyl/forms.py
"""
In dieser Datei werden Formulare/Eingabefelder der webvinyl-App definiert, die auf der Website verwendet werden.
"""

from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Post, Comment

class MusicSearchForm(forms.Form):
    MusicSearchWord = forms.CharField(label='Suchwort', max_length=128)
    key_norm = forms.HiddenInput()
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        labels = {
            'content': _('Post schreiben:'),
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': _('Kommentar schreiben:'),
        }        

class AdvancedSearchForm(forms.Form):
    artist = forms.CharField(required=False, max_length=100, label='Künstler')
    name = forms.CharField(required=False, max_length=100, label='Titel')
    number = forms.CharField(required=False, max_length=100, label='Katalognummer')
    label = forms.CharField(required=False, max_length=100, label='Label')
    key_adv = forms.HiddenInput()

class UserSearchForm(forms.Form): 
    username = forms.CharField(label='Your name', max_length=64)

webvinyl/views.py
"""
In dieser Datei werden die Logiken definiert, die beim Aufruf einer URL der webvinyl-App ausgeführt werden.
"""

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views.generic import (
    UpdateView,
    DeleteView
)
from .forms import UserSearchForm, MusicSearchForm, PostForm, CommentForm, AdvancedSearchForm
from users.forms import UserUpdateForm, ProfileUpdateForm
from django.shortcuts import redirect
from users.models import User 
from django.contrib.auth.decorators import login_required
from utils.discogs_search import basic_search, vinyl_search, advanced_search
from utils.spotify_search import get_spotify_uri
from .models import Post, Album, Comment
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages

@login_required
def base(request):
    user = request.user
    all_follows = user.profile.follows.all()
    own_posts = Post.objects.filter(author=user.profile)
    followee_posts = Post.objects.filter(author__in=all_follows)
    all_posts = own_posts | followee_posts
    posts = all_posts.distinct().order_by('-date_posted')

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user.profile
            post.published_date = timezone.now()
            post.save()
            return redirect('base')
    else:
        form = PostForm()
    return render(request, 'webvinyl/news.html', {'form': form, 'posts':posts})

@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post).order_by('date_posted')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user.profile
            comment.published_date = timezone.now()
            comment.post = post
            comment.save()
            return redirect('post-detail', pk=post.pk)
    else:
        form = CommentForm()  
    return render(request, 'webvinyl/post_detail.html', {'form': form, 'post':post, 'comments': comments})      



class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['content']

    def form_valid(self, form):
        form.instance.author = self.request.user.profil
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user.profile == post.author:
            return True
        return False    

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post   
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user.profile == post.author:
            return True
        return False         
   
@login_required
def search_user(request):
    if request.method == "POST":
        form = UserSearchForm(request.POST)
        if form.is_valid():            
            return redirect('found_user', request.POST.get("username", ""))
    else:
        form = UserSearchForm()    
    return render(request, 'webvinyl/search_user.html', {'form': form})    

@login_required
def found_user(request, usearch):
    searchword = usearch
    users = User.objects.filter(username__contains=usearch)
    return render(request, 'webvinyl/found_user.html', {'users':users, 'searchword':searchword})

@login_required
def search_music(request):
    if request.method == "POST":
        form = MusicSearchForm(request.POST)
        if form.is_valid():
            return redirect('found_music', change=1)  
    else:
        form = MusicSearchForm()    
    return render(request, 'webvinyl/search_music.html', {'form': form})     

@login_required
def adv_search_music(request): 
    if request.method == "POST":
        form = AdvancedSearchForm(request.POST)
        if form.is_valid():
            return redirect('found_music', change=2)  
    else:
        form = AdvancedSearchForm()  
    return render(request, 'webvinyl/adv_search_music.html', {'form': form}) 


@login_required
def found_music(request, change):
    if request.method == "POST":
        if change==2:
            artist = request.POST.get("artist")
            catno = request.POST.get("number")
            label = request.POST.get("label")
            title = request.POST.get("name")
            vinyls = advanced_search(artist, title, catno, label)
            searchwords = []
            if artist: searchwords.append("Künstler: " + artist)
            if title: searchwords.append("Titel: " + title)
            if label: searchwords.append("Label: " + label)
            if catno: searchwords.append("Katalognummer: " + catno)
            searchword = ", ".join(str(x) for x in searchwords)
        else:
            searchword = request.POST.get("MusicSearchWord")
            vinyls = basic_search(searchword)
    else:    
        form = MusicSearchForm()
        
    return render(request, 'webvinyl/found_music.html', {"vinyls":vinyls, "searchword":searchword,})    
 

@login_required
def vinyl_detail(request, masterid):
    
    vinyl = vinyl_search(masterid) 
    in_collection = request.user.profile.albums.filter(pk=vinyl["id"]).exists()
    try:
        spotify_uri = get_spotify_uri(vinyl["title"], vinyl["artist"])
    except:
        spotify_uri = ""
    return render(request, 'webvinyl/vinyl_detail.html', {'vinyl':vinyl, 'id':masterid, 'spotify_uri':spotify_uri, 'in_collection':in_collection})    

@login_required
def follower(request, pk):
    followed_user = get_object_or_404(User, pk=pk)
    followed = followed_user.profile.followed_by.all()
    follower_count = len(followed_user.profile.followed_by.all())
    return render(request, 'webvinyl/follower_list.html', {'followed': followed, 'follower_count': follower_count, 'followed_user': followed_user})

@login_required
def following(request):
    follows = request.user.profile.follows.all()
    return render(request, 'webvinyl/following.html',{'follows':follows})    

@login_required
def add_album(request, albumkey):
    try:
        to_add = Album.objects.get(pk=albumkey)
    except:
        vinyl = vinyl_search(albumkey)
        to_add = Album(vinyl["id"], vinyl["artist"], vinyl["title"], vinyl["cover_art"])
        to_add.save()
    user = request.user
    if to_add in user.profile.albums.all():
        user.profile.albums.remove(to_add)
    else:
        user.profile.albums.add(to_add)
        s ="hat das Album "+to_add.title+" von "+to_add.artist +" hinzugefügt."
        post = Post(content=s, author=request.user.profile)
        post.save()
    return redirect('vinyl_detail', masterid=to_add.pk)

@login_required
def like(request, postkey):
    to_like = get_object_or_404(Post, pk=postkey)
    user = request.user
    if user.profile in to_like.favourite.all():
        to_like.favourite.remove(user.profile)
    else:
        to_like.favourite.add(user.profile)
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)

@login_required
def profile(request, pk):
    follows = request.user.profile.follows.all()
    user = request.user
    if user.pk != pk:
        user = get_object_or_404(User, pk=pk)
  
    follower_count = len(user.profile.followed_by.all())
    follow_count = len(request.user.profile.follows.all())
    collection = user.profile.albums.all()
    return render(request, 'webvinyl/profile.html', {'profile_user': user, 'profile_data': user.profile, 'follows': follows, 'follower_count': follower_count, 'follow_count': follow_count, 'collection': collection,})
        
@login_required
def follow(request, profilekey):
    to_follow = get_object_or_404(User, pk=profilekey)
    user = request.user
    if user.profile in to_follow.profile.followed_by.all():
        user.profile.follows.remove(to_follow.profile)
    else:
        user.profile.follows.add(to_follow.profile)
    return redirect('profile', pk=to_follow.pk)

@login_required
def update(request):
    user = request.user
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=user.profile)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, f'Dein Account wurde geändert.')
            return redirect('profile', pk=user.pk)
    else:
        p_form = ProfileUpdateForm(instance=user.profile)

    context ={
        'p_form':p_form,
        'profile_user':user
    }
    return render(request, 'webvinyl/update.html', context)

webvinyl/templates/webvinyl/adv_search_music.html
{% extends 'webvinyl/base.html' %}
{% load crispy_forms_tags %}
<!-- Auf dieser Page, wird über ein vorher definiertes Formular die erweiterte Musiksuche geladen -->

{% block content %}
<br>
<form method="POST" action="{% url 'found_music' change=2 %}">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Erweiterte Suche</legend>
        {{ form|crispy }}
    </fieldset>
    <div class ="form-group">
        <button type="submit" class="btn btn-outline-info">Suchen</button>
    </div>
</form> 


{% endblock %}

webvinyl/templates/webvinyl/base.html
{% load static %}

<!-- Diese Base-HTML stellt die obere Menüleiste dar -->
<!DOCTYPE html>
<html lang="de">
<head>
  <title>WebVinyl</title>
  <meta charset="utf-8">
  <link rel="icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'webvinyl/site.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-sm navi navbar-light fixed-top">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="{% url 'base' %}">
      <img src="{% static 'image/Logo.png' %}" alt="logo" style="width:160px;">
    </a>
    <!-- Buttontoggle-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'base' %}">Newsfeed</a>
        </li>
        <li class="nav-item follow-mobile">
          <a class="nav-link" href="{% url 'following' %}">Meine Follows</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'search_user' %}">User suchen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'search_music' %}">Musik suchen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' pk=user.pk %}">Profil</a>
        </li>
        <li class="nav-item logout">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <!-- Sidebar -->
      <div class="col-sm-2 sidebar flist">
        <div class="px-3 sidebar-sticky">
          {% include 'webvinyl/follow.html' %}
        </div>
      </div>
      <!-- Main -->
      <div role="main" class="col-sm-10 px-5 ml-auto bg-light">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

</body>
</html>

webvinyl/templates/webvinyl/follower_list.html
{% extends 'webvinyl/base.html' %}
<!-- Diese Datei stellt die Followliste jedes Users dar -->
{% load static %}
{% block content %}
<ul class="nav flex-column">
    <li class="nav-item">
        <h4>Follower von {{ followed_user.username }} <span class="badge badge-pill badge-secondary">{{ follower_count }}</span></h4>
    </li>
    {% for follower in followed %}
        <li class="nav-item">
            <a class="nav-link follow-user" href="{% url 'profile' pk=follower.user.pk %}">
                <img class="rounded-circle" height="25px" width="25px" src="{{ follower.image.url }}">
                {{ follower.user.username }}
            </a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

webvinyl/templates/webvinyl/following.html
{% extends 'webvinyl/base.html' %}
{% load static %}
{% block content %}
<br>
<h4 style="text-decoration: underline">Meine Follows:</h4>
{% for follower in follows %}
<div class="row">
    &emsp;
    <img class="rounded-circle" height="25px" width="25px" src="{{ follower.image.url }}">&nbsp;
    
    <a class="follow-user" href="{% url 'profile' pk=follower.user.pk %}">{{ follower.user.username }}</a>
</div>

<br>
{% endfor %}
{% endblock %}

webvinyl/templates/webvinyl/found_music.html
{% extends 'webvinyl/base.html' %}
<!-- Diese Datei stellt die Suchergebnisse der Musiksuche dar -->

{% block content %}
{% include 'webvinyl/music_searchbar.html' %}
<div class="row mt-3 pl-1">
  <div class="col-sm-12">
    <h2>Gefundene Musik für "{{ searchword }}":</h2>
  </div>
</div>
<div class="row mt-4">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Cover Art</th>
          <th scope="col">Title</th>
          <th scope="col">Artist</th>
          <th scope="col">Label</th>
          <th scope="col">Year</th>
        </tr>
      </thead>
      {% for vinyl in vinyls %}
      <tbody>
        <tr>
          <td>
            <a href="{% url 'vinyl_detail' masterid=vinyl.id %}">
              <img src="{{ vinyl.cover_art }}" alt="Cover Art" style="width:100px;height:100px">
            </a>
          </td>
          <td>
            <a href="{% url 'vinyl_detail' masterid=vinyl.id %}" class="text-secondary">{{ vinyl.title }}</a>
          </td>
          <td>
            {{ vinyl.artist }}
          </td>
          <td>
            {{ vinyl.label }}
          </td>
          <td>
            {{ vinyl.year }}
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

webvinyl/templates/webvinyl/found_user.html
{% extends 'webvinyl/base.html' %}

<!-- Diese Datei stellt die Suchergebnisse der Usersuche dar -->

{% block content %}
<br>
<h2>Gefundene User für: "{{ searchword }}"</h2>

{% for user in users %}
<hr>
<img class="rounded-circle" src="{{ user.profile.image.url }}" alt=".."height="50" width="50">&nbsp;
<a class="follow-user" href="{% url 'profile' pk=user.pk %}">{{ user }}</a>
{% endfor %}
<hr>
{% endblock %}

webvinyl/templates/webvinyl/music_searchbar.html
<!-- Diese Datei stellt die Suchleiste der Musiksuche dar -->


<div class="row">
  <div class="col-sm-12">
    <form action="{% url 'found_music' change=1 %}" method="POST">{% csrf_token %}
      <div class="input-group">
        <input id="MusicSearchWord" name="MusicSearchWord" type="text" class="form-control" placeholder="Suche">
        <div class="input-group-btn">
          <button id="searchButton" class="btn btn-outline-secondary" type="submit" onclick="show_spinner()">
            Los!
          </button>
        </div>
      </div>
    </form> 
    <small class="text-muted">
        <a class="ml-2" href="{% url 'adv_search_music' %}">Erweiterte Suche</a>
    </small>
  </div>
</div>
<div class="row mt-4">
  <div class="col-sm-12">
    <div id="spinner" class="container-fluid" style="display:none">
      <div class="d-flex justify-content-center">
        <div class="spinner-border text-danger" style="width: 4rem; height: 4rem;" role="status">
          <span class="sr-only">Lade...</span>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
function show_spinner()
{
    document.getElementById("spinner").style.display="block";  
}
</script>

webvinyl/templates/webvinyl/news.html
{% extends 'webvinyl/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<!-- Diese Datei stellt die Newsseite dar. Fungiert als Startseite -->

<form method="POST">
  {% csrf_token %}
  <div class="row">
    <div class="col-sm-8">
      <div class="news card">
        <div class="news-header card-header">
          <h5 class="mb-0">Post schreiben</h5>
        </div>
        <div class="news-body card-body">
          <textarea class="form-control" name="content" placeholder="Was möchtest du sagen?" id="id_content" rows="3"></textarea>
          <input class="btn btn-secondary mt-3" type="submit" value="Posten">
        </div>
      </div>
    </div>
  </div>
</form>

<!-- Newsfeed -->
<div class="row">
  <div class="col-sm-8 mt-3">
    <div class="news card">
      <div class="news-header card-header">
        <h5 class="mb-0">Newsfeed</h5>
      </div>
      <div class="news-body card-body">
        {% for post in posts %}
          <div class="card mb-3">
            <div class="card-body">
              <div class="media">
                <!-- User image, name, and post date -->
                <img class="rounded-circle mx-2" height="30px" width="30px" src="{{ post.author.image.url }}">
                <div class="media-body">
                  <h5 class="mb-3">
                    <a class="mr-2 follow-user" href="{% url 'profile' pk=post.author.user.pk %}">{{ post.author.user.username }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                  </h5>
                  <!-- Post content -->
                  <p><span class="post-text">{{ post.content }}</span></p>
                  <!-- Number of Likes/Comments -->
                  <span class="text-muted">
                    {{ post.favourite.all|length }} Likes /
                  </span>
                  {% if post.comments.all|length == 1 %}
                    <span class="text-muted">
                      <a class="text-muted" href="{% url 'post-detail' pk=post.pk %}">{{ post.comments.all|length }} Kommentar</a>
                    </span>
                  {% else %}
                    <span class="text-muted" style="margin-bottom: 0">
                      <a class="text-muted" href="{% url 'post-detail' pk=post.pk %}">{{ post.comments.all|length }} Kommentare</a>
                    </span>
                  {% endif %}
                  <hr>
                  <!-- Like and Comment buttons -->
                  <div class="row">
                    <form action="{% url 'like-post' postkey=post.pk %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      {% if user.profile in post.favourite.all %}
                        <input type="submit" name="like" value="Like" class="btn btn-outline-success text-success mx-3" style="font-weight: bold">
                      {% else %}
                        <input type="submit" name="like" value="Like" class="btn btn-outline-secondary text-secondary mx-3">
                      {% endif %}
                    </form>
                    <a class="btn btn-outline-secondary text-secondary" href="{% url 'post-detail' pk=post.pk %}">
                      Kommentieren
                    </a>
                  </div>

                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<script>
$("#id_content").keypress(function (e) {
    if(e.which == 13 && !e.shiftKey) {        
        $(this).closest("form").submit();
        e.preventDefault();
        return false;
    }
});
</script>
{% endblock %}

webvinyl/templates/webvinyl/post_confirm_delete.html
{% extends 'webvinyl/base.html' %}
<!-- Diese Datei stellt die Sicherheitsfrage vor dem Löschen eines Posts dar -->


{% block content %}
<br>
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Post löschen</legend>
        <h2>Sind Sie sich sicher, das Sie den Post löschen wollen?</h2>
    </fieldset>
    <div class ="form-group">
        <button type="submit" class="btn btn-outline-danger">Ja, Löschen</button>
        <a href="{% url 'post-detail' object.id %}" class="btn btn-outline-secondary">Abbrechen</a>
    </div>
</form> 


{% endblock %}

webvinyl/templates/webvinyl/post_form.html
{% extends 'webvinyl/base.html' %}
{% load crispy_forms_tags %}
<!-- Diese Datei stellt das Eingabefeld für Posts dar -->


{% block content %}
<br>
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Post verfassen</legend>
        {{ form|crispy }}
    </fieldset>
    <div class ="form-group">
        <button type="submit" class="btn btn-outline-info">Senden</button>
    </div>
</form> 


{% endblock %}

webvinyl/templates/webvinyl/search_music.html
{% extends 'webvinyl/base.html' %}
<!-- Diese Datei stellt die Musiksuche dar -->

{% block content %}
{% include 'webvinyl/music_searchbar.html' %}

{% endblock %}

webvinyl/templates/webvinyl/update.html
{% extends 'webvinyl/base.html' %}
<!-- Diese Datei stellt ein Formular zum Updaten von Posts dar -->

{% load crispy_forms_tags %}

{% block content %}
    <div class="row mt-4">
      <div class="col-sm-2">
          <img class="rounded-circle" height="125px" width="125px" src="{{ profile_user.profile.image.url }}">
      </div>
      <div class="col-sm-8">
        <br>
        <h1>Profil von {{ profile_user.username }}</h1>
      </div>
      
    </div>
    <div class="container">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profil ändern</legend>
                {{ p_form|crispy }}
            </fieldset>
            <div class ="form-group">
                <button type="submit" class="btn btn-outline-info">Speichern</button>
            </div>
        </form> 
      </div>
{% endblock %}